version: "3"

services:
  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"

  app:
    build: ./app
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./app/docker.env
    depends_on:
      - redis

  redis:
    image: redis
